### ISSUE TITLE
New wallpaper get downloaded with the Bing Watermark

### ISSUE THREAD

**Issue by vmonichon** [timothymctim/Bing-wallpapers#4]
It seems that the last few wallpapers it downloaded are all watermarked.

If I try manually i.e:

www.bing.com/th?id=OHR.CormorantMackerel_EN-US7682867267_1920x1080.jpg

The watermark is not present. Though the URL is different in the script:

https://www.bing.com/HPImageArchive.aspx?......

**Comment by timothymctim** [comment]
Thanks for reporting. Could you maybe share some more information if this problem persists for you? I haven’t seen a watermark added to the pictures yet. The script checks using the second link (e.g., https://bing.com/HPImageArchive.aspx?format=xml&idx=0&n=3) for the right image location and then downloads the wallpaper by adapting the URL from the `urlBase` tag.

**Comment by vmonichon** [comment]
Hi,
Yes, I'm running a scheduled task with the following parameter:
-WindowStyle Hidden -file C:\Users\vmc\Documents\WindowsPowerShell\Scripts\bing-wallpapers.ps1 -files 0 -locale "en-US" -resolution auto

The auto resolution elect the 1920x1200 resolution to be downloaded.

I have attached today file:
![2020-01-18](https://user-images.githubusercontent.com/47193032/72668838-df584c80-39f8-11ea-82df-31d0649090c1.jpg)

I do see in the xml the url tag is bringing back this url:
https://bing.com//th?id=OHR.GypsumSand_EN-US7746438548_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp

And yes the result does not have the watermark, but it come back as a jfif file format.

If I consider only the first part:
https://bing.com/th?id=OHR.GypsumSand_EN-US7746438548_1920x1080.jpg
Then it comes as a jpeg and without the watermark:
![th](https://user-images.githubusercontent.com/47193032/72668909-b2586980-39f9-11ea-8bbc-55b2bd90ffb1.jpg)


Not quite sure what's going on. Notice that all the picture above lead to 1920x1080

I see in the code you are using the urlbase xml tag, so using it so manually with the resolution the auto is using my machine:

https://bing.com/th?id=OHR.CormorantMackerel_EN-US7682867267_1920x1200.jpg

I was able to reproduce:

![OHR GypsumSand_EN-US7746438548_1920x1200](https://user-images.githubusercontent.com/47193032/72668993-81c4ff80-39fa-11ea-8fd0-bd64a6722d04.jpg)

So I think the issue is the resolution, they seem to push images that are watermarked.

Thank anyway. Great work with the script ;)

**Comment by timothymctim** [comment]
I tried to find some other URLs to see if they are watermarked as well, but I guess Bing couldn’t publish these high-res photos without a watermark. Thanks for your understanding and well-written bug report!
