### ISSUE TITLE
1280x1024 resolution

### ISSUE THREAD

**Issue by Jadjld** [timothymctim/Bing-wallpapers#5]
Can you add/is it possible to add this resolution?, i need it and would be very useful for me
Thanks in advance

**Comment by timothymctim** [comment]
I would love to add it, but I don’t believe it’s provided by Bing. Bing only provides a limited set of dimensions, e.g., [1920x1080](https://www.bing.com/th?id=OHR.MarathonSunday_ROW0781350526_1920x1080.jpg) and [1366x768](https://www.bing.com/th?id=OHR.MarathonSunday_ROW0781350526_1366x768.jpg), but alas no [1280x1024](https://www.bing.com/th?id=OHR.MarathonSunday_ROW0781350526_1280x1024.jpg). You could choose the biggest image format you want and then select “Center,” “Fill,” “Fit,” “Stretch,” “Tile,” or “Span” the background image under the Background settings.

**Comment by Jadjld** [comment]
Ok. Thank you very much for your time and project. A last question, how can I choose a bigger image format? The script always gives me 1280x720 images.

**Comment by timothymctim** [comment]
That should be possible using the script’s arguments. For example, add `-resolution '1920x1080'`. See the project’s [README](../blob/master/README.md).
